/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../next.config`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/layout`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/page`; params?: Router.UnknownInputParams; } | { pathname: `/../src/lib/api`; params?: Router.UnknownInputParams; } | { pathname: `/../src/providers/QueryProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../src/theme/colors`; params?: Router.UnknownInputParams; } | { pathname: `/../src/theme/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/types/pokemon`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/usePokemon`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/PokemonCard`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/PokemonModal`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/ErrorMessage`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/LoadingSpinner`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/../next.config`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/app/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/app/page`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/lib/api`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/providers/QueryProvider`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/theme/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/theme/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/types/pokemon`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/hooks/usePokemon`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/PokemonCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/PokemonModal`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/SearchBar`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/ErrorMessage`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/LoadingSpinner`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/../next.config${`?${string}` | `#${string}` | ''}` | `/../src/app/layout${`?${string}` | `#${string}` | ''}` | `/../src/app/page${`?${string}` | `#${string}` | ''}` | `/../src/lib/api${`?${string}` | `#${string}` | ''}` | `/../src/providers/QueryProvider${`?${string}` | `#${string}` | ''}` | `/../src/theme/colors${`?${string}` | `#${string}` | ''}` | `/../src/theme/index${`?${string}` | `#${string}` | ''}` | `/../src/types/pokemon${`?${string}` | `#${string}` | ''}` | `/../src/hooks/usePokemon${`?${string}` | `#${string}` | ''}` | `/../src/components/PokemonCard${`?${string}` | `#${string}` | ''}` | `/../src/components/PokemonModal${`?${string}` | `#${string}` | ''}` | `/../src/components/SearchBar${`?${string}` | `#${string}` | ''}` | `/../src/components/ErrorMessage${`?${string}` | `#${string}` | ''}` | `/../src/components/LoadingSpinner${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../next.config`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/layout`; params?: Router.UnknownInputParams; } | { pathname: `/../src/app/page`; params?: Router.UnknownInputParams; } | { pathname: `/../src/lib/api`; params?: Router.UnknownInputParams; } | { pathname: `/../src/providers/QueryProvider`; params?: Router.UnknownInputParams; } | { pathname: `/../src/theme/colors`; params?: Router.UnknownInputParams; } | { pathname: `/../src/theme/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/types/pokemon`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/usePokemon`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/PokemonCard`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/PokemonModal`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/ErrorMessage`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/LoadingSpinner`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
